
image: 
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - robocorp.robotframework-lsp
    - ms-python.black-formatter
    - ms-python.python
    - njpwerner.autodocstring
  
ports:
  - name: runserver
    port: 3000

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false

tasks:
  - name: Install deps
    before: |
      cp .gitpod.settings.json /workspace/.vscode-remote/data/Machine/settings.json
      pip install prowler==4.4.1 cryptography==43.0.1

      # Get Latest Terraform
      LATEST_TERRAFORM_VERSION=$(curl -s https://releases.hashicorp.com/terraform/ | \
      grep -oP 'terraform_\K([0-9]+\.[0-9]+\.[0-9]+)' | grep -vE '[-]' | sort -Vr | \
      while read version; do \
          if wget -q --spider "https://releases.hashicorp.com/terraform/${version}/terraform_${version}_linux_amd64.zip"; then \
              echo "$version"; break; \
          fi; \
      done) && \
      echo "Latest available Terraform version: $LATEST_TERRAFORM_VERSION" && \
      wget https://releases.hashicorp.com/terraform/${LATEST_TERRAFORM_VERSION}/terraform_${LATEST_TERRAFORM_VERSION}_linux_amd64.zip && \
      unzip terraform_${LATEST_TERRAFORM_VERSION}_linux_amd64.zip && \
      sudo mv terraform /usr/local/bin/ && \
      rm terraform_${LATEST_TERRAFORM_VERSION}_linux_amd64.zip

      brew install go-task/tap/go-task
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      brew install yq
      npm install ajv
      sudo az aks install-cli
    command: |
      pip install --user --no-cache-dir -r /workspace/codecollection-devtools/codecollection/requirements.txt


  - name: Run log server
    command: |
      mkdir -p $ROBOT_LOG_DIR 
      python -m http.server --bind 0.0.0.0 --directory $ROBOT_LOG_DIR 3000
