version: '3.9'
services:
  devtools:
    container_name: devtools
    user: runwhen
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - RW_MODE=dev
    volumes:
      - .:/home/runwhen
    ports:
      - 3000:3000
