version: '3.9'
# LOCAL DEV
services:
  devtools:
    container_name: devtools
    user: runwhen
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      # Mount local codebase to reflect changes for local dev
      - .:/home/runwhen
    ports:
      - 3000:3000
