name: Build And Push

on:
  push:
    branches:    
      - main

# TODO: Implement semver tagging
env:
  TAG: latest
  DOCKERFILE: Dockerfile
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -f ${{ env.DOCKERFILE }} -t ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.TAG }} .
      - name: Push
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username ${{ github.actor }} --password-stdin ${{ env.REGISTRY }}
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.TAG }}