name: Smoke Test Source Build

on:
  push:
  workflow_dispatch:

env:
  CC_REPO: https://github.com/runwhen-contrib/rw-public-codecollection.git
  CC_REPO_PATH: rw-public-codecollection
  TEST_CODEBUNDLE_PATH: /app/codecollection/codebundles/http-ok/sli.robot
  CURL_URL: http://localhost:3000/http-ok/sli-log.html

jobs:
  smoke-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint ro
        run: |
          shellcheck ro --severity=warning
      - name: Clone template Repo & Prep ENV
        run: |
          git clone ${{ env.CC_REPO }} \
          && mv ${{ env.CC_REPO_PATH }} codecollection \
          && sudo chown -R 1000:0 codecollection \
          && touch .env
      - name: Build Container
        run: |
          docker compose up -d --build devtools
      - name: Install CodeCollection Dependencies
        run: |
          docker compose exec devtools bash -c "pip install --user --no-cache-dir -r /app/codecollection/requirements.txt"
      - name: Run Codebundle
        run: |
          docker compose exec devtools bash -c "ro ${{ env.TEST_CODEBUNDLE_PATH }} && ls -R /robot_logs"
      - name: Check Log Accessible
        run: |
          curl --fail-with-body ${{ env.CURL_URL }}
      